services:
   webapp:
      container_name: web_api
      depends_on:
         - db
         - redis
      build:
         context: .
         dockerfile: src/presentation/DELAY.Presentation.RestAPI/Dockerfile
      ports:
         - "8081:8081"
         - "8080:8080"
      environment:
         - AASPNETCORE_ENVIRONMENT=Development
         - ASPNETCORE_URLS=https://+:8081;http://+:8080
         - ASPNETCORE_Kestrel__Certificates__Default__Password=1111
         - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificateForServerAuthorization.pfx
      volumes:
         - ~/.aspnet/https:/https:ro
         - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

   db:
      container_name: pg_db
      image: postgres:16.4
      environment:
         POSTGRES_DB: "delay_db"
         POSTGRES_USER: "sa"
         POSTGRES_PASSWORD: "pg1111"
      ports:
         - "8001:5432"
      volumes:
         - pgdb:/var/lib/postgresql/data

   redis:
      container_name: delay-redis
      image: redis:latest
      environment:
         REDIS_HOST: delay-redis
         REDIS_PORT: 6379
      ports:
         - 6379:6379
      restart: always

volumes:
   pgdb:
